### PR TITLE
Bump cookie-rs dependency.

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by nox** [comment]
@aelita-mergebot r+

**Comment by nox** [comment]
@frewsxcv So... I'm confused... Why did we need that, when hyper 0.9 never depended on cookie 0.4, and only cookie 0.2..?

**Comment by frewsxcv** [comment]
It was for [my openssl pr at the time](https://github.com/servo/servo/pull/14484/files#diff-ae2d281f7aac5fdc9f53151431da9e68L16). IIRC in that PR, I disabled cookie-rs support in Hyper via `no-default-features` and just bumped Servo's cookie-rs dep.

**Comment by nox** [comment]
capture d ecran 2017-02-11 a 01 12 13

Should have known better than to trust crates.io! Will go cry in a corner.

**Comment by nox** [comment]
I'll keep the cookie bump reverted though, because webdriver also depends on cookie 0.2 and that would just make the serde bump even larger.

**Comment by nox** [comment]
@frewsxcv Seems like you conflated `default-features = false` with `optional = true`. AFAICT `cookie` was never optional in `hyper` 0.9.

**Comment by frewsxcv** [comment]
I really don't remember what I was doing. Maybe I was turning off `cookie/secure` https://github.com/hyperium/hyper/blob/0.9.x/Cargo.toml#L56 to avoid bringing in an old openssl

**Comment by nox** [comment]
No problem. :)

**Pull request merged**
